### ISSUE TITLE
Tailscale not restarting after update

### ISSUE THREAD

**Issue by bdoell88** [NeedsCoffee/Tailscale-Updater-Windows#3]
I have this on place on all of my machines and it seems that the updater is working, but the tailscale app is not restarting on its own, so the endpoint will stay offline until I either reboot or run tailscale from the start menu.

**Comment by NeedsCoffee** [comment]
Thanks @bdoell88. Strange. That's not my experience, rather the service updates and the client comes back online but the client-visible system tray app doesn't reappear until a logout and login, or a reboot. I did notice that but never found a way around it. Most likely it is because the system tray app needs to run in the user context, but the update task runs as system and causes the tray app to start as system as well... I'll have another go but can possibly double check if your clients really do or don't come back online after an update? I wonder if it's an artifact of the latest 1.18.x client if you're certain.
Thanks

**Comment by bdoell88** [comment]
I can confirm that. Here is a screenshot from my tailscale admin page. The one that is connected is after i manually re-ran the tray app. I have 7 windows PC's and have same experience for each one.

![image](https://user-images.githubusercontent.com/70822874/146386136-3d472d80-4f38-40fc-86e3-58d7bab13538.png)

**Comment by NeedsCoffee** [comment]
@bdoell88 I've released v0.4.0 which targets this issue. Could you try it out and see if helps your situation?

**Comment by bdoell88** [comment]
It works! I installed the latest version, then installed an older version of tailscale and ran the scheduled task. It updated and restarted the app on its own.

Thank you!!

**Comment by NeedsCoffee** [comment]
Thanks for reporting it and for the help testing! That's excellent news :)
